/*
Klarity Integrations

REST API for managing Estate Records using Klarity Integrations. You can enrich your estate by creating new kinds of estate records or extending existing ones. Before making use of the API, you must first register your External Integration in Klarity, which provides you with the required authentication credentials. Then, you use those credentials to obtain a Token that allows you to make authorized calls to Klarity’s REST API for External Integration.

API version: 0.0.3
Contact: products@nordcloud.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package integrations

import (
	"encoding/json"
)

// EstateRecordsDeleteBodyRecords struct for EstateRecordsDeleteBodyRecords
type EstateRecordsDeleteBodyRecords struct {
	// Nordcloud ID of a resource in Klarity.
	Nid *string `json:"nid,omitempty"`
	// Internal ID of a resource.
	Id *string `json:"id,omitempty"`
	// Friendly name of a resource (id will be used, if not provided).
	Name *string `json:"name,omitempty"`
	// Type of a resource (resourceType/extension) can contain just type, eg `jira` or with subtypes separated by \"/\" symbol.
	Type *string `json:"type,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _EstateRecordsDeleteBodyRecords EstateRecordsDeleteBodyRecords

// NewEstateRecordsDeleteBodyRecords instantiates a new EstateRecordsDeleteBodyRecords object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEstateRecordsDeleteBodyRecords() *EstateRecordsDeleteBodyRecords {
	this := EstateRecordsDeleteBodyRecords{}
	return &this
}

// NewEstateRecordsDeleteBodyRecordsWithDefaults instantiates a new EstateRecordsDeleteBodyRecords object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEstateRecordsDeleteBodyRecordsWithDefaults() *EstateRecordsDeleteBodyRecords {
	this := EstateRecordsDeleteBodyRecords{}
	return &this
}

// GetNid returns the Nid field value if set, zero value otherwise.
func (o *EstateRecordsDeleteBodyRecords) GetNid() string {
	if o == nil || o.Nid == nil {
		var ret string
		return ret
	}
	return *o.Nid
}

// GetNidOk returns a tuple with the Nid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstateRecordsDeleteBodyRecords) GetNidOk() (*string, bool) {
	if o == nil || o.Nid == nil {
		return nil, false
	}
	return o.Nid, true
}

// HasNid returns a boolean if a field has been set.
func (o *EstateRecordsDeleteBodyRecords) HasNid() bool {
	if o != nil && o.Nid != nil {
		return true
	}

	return false
}

// SetNid gets a reference to the given string and assigns it to the Nid field.
func (o *EstateRecordsDeleteBodyRecords) SetNid(v string) {
	o.Nid = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EstateRecordsDeleteBodyRecords) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstateRecordsDeleteBodyRecords) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EstateRecordsDeleteBodyRecords) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EstateRecordsDeleteBodyRecords) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *EstateRecordsDeleteBodyRecords) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstateRecordsDeleteBodyRecords) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *EstateRecordsDeleteBodyRecords) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *EstateRecordsDeleteBodyRecords) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *EstateRecordsDeleteBodyRecords) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EstateRecordsDeleteBodyRecords) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *EstateRecordsDeleteBodyRecords) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *EstateRecordsDeleteBodyRecords) SetType(v string) {
	o.Type = &v
}

func (o EstateRecordsDeleteBodyRecords) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Nid != nil {
		toSerialize["nid"] = o.Nid
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *EstateRecordsDeleteBodyRecords) UnmarshalJSON(bytes []byte) (err error) {
	varEstateRecordsDeleteBodyRecords := _EstateRecordsDeleteBodyRecords{}

	if err = json.Unmarshal(bytes, &varEstateRecordsDeleteBodyRecords); err == nil {
		*o = EstateRecordsDeleteBodyRecords(varEstateRecordsDeleteBodyRecords)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "nid")
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "type")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableEstateRecordsDeleteBodyRecords struct {
	value *EstateRecordsDeleteBodyRecords
	isSet bool
}

func (v NullableEstateRecordsDeleteBodyRecords) Get() *EstateRecordsDeleteBodyRecords {
	return v.value
}

func (v *NullableEstateRecordsDeleteBodyRecords) Set(val *EstateRecordsDeleteBodyRecords) {
	v.value = val
	v.isSet = true
}

func (v NullableEstateRecordsDeleteBodyRecords) IsSet() bool {
	return v.isSet
}

func (v *NullableEstateRecordsDeleteBodyRecords) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEstateRecordsDeleteBodyRecords(val *EstateRecordsDeleteBodyRecords) *NullableEstateRecordsDeleteBodyRecords {
	return &NullableEstateRecordsDeleteBodyRecords{value: val, isSet: true}
}

func (v NullableEstateRecordsDeleteBodyRecords) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEstateRecordsDeleteBodyRecords) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


