# coding: utf-8

"""
    Klarity Integrations

    REST API for managing Estate Records using Klarity Integrations. You can enrich your estate by creating new kinds of estate records or extending existing ones. Before making use of the API, you must first register your External Integration in Klarity, which provides you with the required authentication credentials. Then, you use those credentials to obtain a Token that allows you to make authorized calls to Klarity’s REST API for External Integration.  # noqa: E501

    The version of the OpenAPI document: 0.0.5
    Contact: products@nordcloud.com
    Generated by: https://openapi-generator.tech
"""

from klarity_integrations.paths.v1_enrichments_estate_records.post import V1EnrichmentsEstateRecordsPost
from klarity_integrations.paths.v1_estate_records.delete import V1EstateRecordsDelete
from klarity_integrations.paths.v1_estate_records.post import V1EstateRecordsPost


class KlarityIntegrationsApi(
    V1EnrichmentsEstateRecordsPost,
    V1EstateRecordsDelete,
    V1EstateRecordsPost,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
