"""
    Klarity Integrations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import unittest

import klarity_integrations
from klarity_integrations.api.klarity_integrations_api import KlarityIntegrationsApi  # noqa: E501


class TestKlarityIntegrationsApi(unittest.TestCase):
    """KlarityIntegrationsApi unit test stubs"""

    def setUp(self):
        self.api = KlarityIntegrationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_v1_estate_records_post(self):
        """Test case for v1_estate_records_post

        Manage Klarity estate records  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
