"""
    Klarity Integrations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import klarity_integrations
from klarity_integrations.model.estate_records_request_body_records import EstateRecordsRequestBodyRecords
globals()['EstateRecordsRequestBodyRecords'] = EstateRecordsRequestBodyRecords
from klarity_integrations.model.estate_records_request_body import EstateRecordsRequestBody


class TestEstateRecordsRequestBody(unittest.TestCase):
    """EstateRecordsRequestBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEstateRecordsRequestBody(self):
        """Test EstateRecordsRequestBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EstateRecordsRequestBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
