"""
    Klarity Integrations

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import klarity_integrations
from klarity_integrations.model.accepted_response_body import AcceptedResponseBody


class TestAcceptedResponseBody(unittest.TestCase):
    """AcceptedResponseBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAcceptedResponseBody(self):
        """Test AcceptedResponseBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AcceptedResponseBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
