/*
Klarity Integrations

Testing KlarityIntegrationsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package integrations

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/nordcloud/klarity-integrations-sdk/go/integrations"
)

func Test_integrations_KlarityIntegrationsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test KlarityIntegrationsApiService V1EnrichmentsEstateRecordsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KlarityIntegrationsApi.V1EnrichmentsEstateRecordsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KlarityIntegrationsApiService V1EstateRecordsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KlarityIntegrationsApi.V1EstateRecordsDelete(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test KlarityIntegrationsApiService V1EstateRecordsPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.KlarityIntegrationsApi.V1EstateRecordsPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
