# Copyright 2021 Nordcloud Oy or its affiliates. All Rights Reserved.

name: Generate SDK client

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Generate SDK
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # Fetch current version of API
      - name: Get current version
        id: version
        run: echo "::set-output name=version::$(grep "version:" ./go/integrations/api/openapi.yaml  | awk -F':' '{print $2}' | sed 's/[",]//g' | tr -d '[[:space:]]')"

      # Fetch remote version of API
      - name: Get remote version
        id: remote_version
        run: echo "::set-output name=version::$(curl -L -s https://integrations-api.klarity.nordcloudapp.com/docs/api.yml | grep "version:" | awk -F':' '{print $2}' | sed 's/[",]//g' | tr -d '[[:space:]]')"

      # Break job if nothing has changed
      - name: Break if versions did not change
        if: steps.version.outputs.version == steps.remote_version.outputs.version
        run: echo "API version did not change, there is no need to build SDK" && exit 1

      # Clear directory to avoid having unused files after generate GO sdk
      - name: Remove Go Files
        run: rm -rf go/integrations

      # Generate a GO client package
      - name: OpenAPI Generator GO Action
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: "generate -c ./.generators/config-go.yml -o ./go/integrations"

      # Clear directory to avoid having unused files after generate Python sdk
      - name: Remove Python Files
        run: rm -rf python/integrations

      # Generate a Python client package
      - name: OpenAPI Generator Python Action
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: "generate -c ./.generators/config-python.yml -o ./python/integrations"

      # Update Python client README.md
      - name: Add subdirectory to Python README.md git url
        run: sudo sed -i 's/klarity-integrations-sdk.git/klarity-integrations-sdk.git#subdirectory=python\/integrations/g' python/integrations/README.md

      # Commit all changes
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
