# Copyright 2021 Nordcloud Oy or its affiliates. All Rights Reserved.

name: Generate SDK client

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Generate SDK
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # Fetch current version of API
      - name: Get current version
        id: version
        run: echo "::set-output name=version::$(grep "version:" ./go/integrations/api/openapi.yaml  | awk -F':' '{print $2}' | sed 's/[",]//g' | tr -d '[[:space:]]')"

      # Fetch remote version of API
      - name: Get remote version
        id: remote_version
        run: echo "::set-output name=version::$(curl -L -s https://integrations-api.klarity.nordcloudapp.com/docs/api.yml | grep "version:" | awk -F':' '{print $2}' | sed 's/[",]//g' | tr -d '[[:space:]]')"

      # Break job if nothing has changed
      - name: Break if versions doesn't change
        if: steps.version.outputs.version == steps.remote_version.outputs.version
        run: echo "API version doesnt change, breaking!" && exit 1

      # Clear directory to avoid having unused files after generate sdk
      - name: Remove File
        run: rm -rf go/integrations

      # Generate a client package
      - name: OpenAPI Generator Action
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: "generate -c ./.generators/config-go.yml -o ./go/integrations"

      # Commit all changes
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
