# Copyright 2021 Nordcloud Oy or its affiliates. All Rights Reserved.

name: Generate SDK client

on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  generate-clients:
    runs-on: ubuntu-latest
    name: Generate SDK
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # Clear directory to avoid having unused files after generate sdk
      - name: Remove File
        run: rm -rf go/integrations

      # Generate a client package
      - name: OpenAPI Generator Action
        uses: kpurdon/openapi-generator-action@v0.0.3
        with:
          args: "generate -c ./.generators/config-go.yml -o ./go/integrations"

      # Commit all changes
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
