# Copyright 2021 Nordcloud Oy or its affiliates. All Rights Reserved.

name: Release SDK client

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Generate SDK client"]
    types:
      - completed

jobs:
  release-clients:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Release SDK
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v2

      # Fetch current version to use for tagging purpose
      - name: Get current version
        id: version
        run: echo "::set-output name=version::$(grep "version:" ./go/integrations/api/openapi.yaml  | awk -F':' '{print $2}' | sed 's/[",]//g' | tr -d '[[:space:]]')"

      # Release GO SDK if there are any new commits since last tag
      - name: Release GO SDK
        id: release-go-sdk
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: go/integrations/v${{ steps.version.outputs.version }}
          release_name: GO v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

     # Release Python SDK if there are any new commits since last tag
      - name: Release GO SDK
        id: release-python-sdk
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: python/integrations/v${{ steps.version.outputs.version }}
          release_name: Python v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
